version: "3.9"
services:
    spring-app:
        build: ./demo/
        ports:
            - 8080:8080
        depends_on: 
            - sql-server
        restart: on-failure
        volumes:
            - /var/www/files:/var/www/html
    sql-server:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=db
        command: --lower_case_table_names=1
        ports:
            - 3306:3306
        volumes:
            - /var/db:/var/lib/mysql
    frontend-app:
        build: ./frontend/
        ports:
            - 80:80
        depends_on:
            - spring-app
        volumes:
            - /var/www/files:/var/www/static/image
        restart: on-failure

