version: "3.9"
services:
    spring-app:
        build: .
        ports:
            - 8080:8080
        depends_on: 
            - sql-server
        restart: on-failure
    sql-server:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=secret
        ports:
            - 3306:3306
        volumes:
            - ./User.sql:/docker-entrypoint-initdb.d/User.sql

