version: "3.9"
services:
    sql-server:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=secret
        ports:
            - 3306:3306
        volumes:
            - ./User.sql:/docker-entrypoint-initdb.d/User.sql
